let griffon = {
    name: "griffon",
    width: 109,
    height: 115,
    states:{
        "jump":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.5,
            animations:[
                {image:"jump0.png",duration:0.2},
                {image:"jump1.png",duration:0.1},
                {image:"jump2.png",duration:0.2},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vx=300*self.direction
                self.vy=-600
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer=="attack"){
                    self.state="jump attack"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"dash0.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash3.png",duration:0.1},
                {image:"dash4.png",duration:0.1},
                {image:"dash5.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vx=350*self.direction
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    if(self.is_grounded==true){
                        self.state=x
                        self.state_buffer="none"
                    }else{
                        if(self.states[x].arial){
                            self.state=x
                            self.state_buffer="none"
                        }
                    }
                   
                }
            },
            end:function(game,obj,self){
                self.vx=0
            }
        },
        "back dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.5,
            animations:[
                {image:"jump0.png",duration:0.2},
                {image:"jump1.png",duration:0.1},
                {image:"jump2.png",duration:0.2},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vx=300*-self.direction
                self.vy=-350
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer=="attack"){
                    self.state="jump attack"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"attack0.png",duration:0.1},
                {image:"attack0.png",duration:0.01,custom:function(game,obj,self){
                    self.vx=100*self.direction
                }},
                {image:"attack1.png",duration:0.09,damage:5,knockback:-100,knockdown:false,stun:0.3,freeze_frame:0.1,offset:{x:30,y:0}},
                {image:"attack2.png",duration:0.1,damage:5,knockback:-100,knockdown:false,stun:0.3,freeze_frame:0.1,offset:{x:30,y:0}},
                {image:"attack3.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:100,h:20},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "special 1":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"special0.png",duration:0.1},
                {image:"special1.png",duration:0.1,
                    custom:function(game,obj,self){
                        special_grab(game,obj,self)
                    }
                },
                {image:"special2.png",duration:0.1}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:80,h:20},
            init:function(game,obj,self){self.vx=0},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "special 2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.9,
            animations:[
                {image:"special20.png",duration:0.1},
                {image:"special21.png",duration:0.1,offset:{x:20,y:0}},
                {image:"special22.png",duration:0.1,offset:{x:30,y:0}},
                {image:"special23.png",duration:0.1,damage:5,knockback:100,knockdown:false,stun:0.3,freeze_frame:0.2,offset:{x:40,y:0}},
                {image:"special24.png",duration:0.1,damage:5,knockback:100,knockdown:false,stun:0.3,freeze_frame:0.2,offset:{x:50,y:0}},
                {image:"special25.png",duration:0.1,damage:5,knockback:100,knockdown:false,stun:0.6,freeze_frame:0.2,offset:{x:50,y:0}},
                {image:"special26.png",duration:0.3,offset:{x:50,y:0}},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:-30,w:120,h:90},
            init:function(game,obj,self){self.vx=0},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "special 3":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.6,
            animations:[
                {image:"special30.png",duration:0.1},
                {image:"special31.png",duration:0.1},
                {image:"special32.png",duration:0.4,
                    custom:function(game,obj,self){
                        self.vx=300*self.direction
                        self.vy=-600
                    }
                }
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:-40,w:60,h:90},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(this.animation_frame==2){
                    special_grab(game,this,self)
                }
            },
            end:function(game,obj,self){self.vx=0}
        },
        "jump attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"jumpattack0.png",duration:0.1},
                {image:"jumpattack1.png",duration:0.1},
                {image:"jumpattack2.png",duration:0.1,damage:5,knockback:-50,knockdown:false,stun:0.3,freeze_frame:0.1,offset:{x:30,y:0}},
                {image:"jumpattack2.png",duration:0.1,damage:5,knockback:-50,knockdown:false,stun:0.3,freeze_frame:0.1,offset:{x:30,y:0}},
                {image:"jumpattack2.png",duration:0.1,damage:5,knockback:-100,knockdown:false,stun:0.5,freeze_frame:0.1,offset:{x:30,y:0}},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:100,h:20},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
            }
        },
        "ultimate":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"special0.png",duration:0.1},
                {image:"special1.png",duration:0.1,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        if(game.physics.aabb(obj.hitbox,opponent,game)){
                            if(opponent.state!="knockdown"){
                                game.playsound("assets/grab.wav")
                                self.state="throwing"
                                opponent.state="being thrown"
                                opponent.x=self.x+(self.w/2)*self.direction
                                opponent.y=self.y
                                self.states["throwing"]={
                                    frames:0,
                                    offsetx:0,
                                    offsety:0,
                                    temps:{},
                                    update:function(self,game){
                                        if(this.frames==0){
                                            self.image="specialgrab0.png"
                                            this.frames=1
                                            self.vy=-1000
                                            self.vx=0
                                            self.is_grounded=false
                                        }
                                        this.frames-=game.dt
                                        if(this.frames<0.2){
                                            self.image="specialgrab1.png"
                                        }
                                        if(this.frames<=0){
                                            this.frames=0
                                            self.state="idle"
                                        }
                                    }
                                }
                                opponent.states["being thrown"]={
                                    frames:0,
                                    offsetx:0,
                                    offsety:0,
                                    temps:{},
                                    update:function(self,game){
                                        if(this.frames==0){
                                            self.image="hit.png"
                                            this.frames=1
                                            self.vy=-1000
                                            self.vx=0
                                            self.is_grounded=false
                                        }
                                        this.frames-=game.dt
                                        if(this.frames<=0){
                                            this.frames=0
                                            self.health-=60
                                            self.knockdown()
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                {image:"special2.png",duration:0.1}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:80,h:20},
            init:function(game,obj,self){self.vx=0},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        }
    }
}

function special_grab(game,obj,self){
    let opponent=game.match.get_opponent(self,game)
    if(game.physics.aabb(obj.hitbox,opponent,game)){
        if(opponent.state!="knockdown"){
            game.playsound("assets/grab.wav")
            self.state="throwing"
            opponent.state="being thrown"
            opponent.x=self.x+(self.w/2)*self.direction
            opponent.y=self.y
            self.states["throwing"]={
                frames:0,
                offsetx:0,
                offsety:0,
                temps:{},
                update:function(self,game){
                    if(this.frames==0){
                        self.image="specialgrab0.png"
                        this.frames=0.6
                        self.vy=-600
                        self.vx=0
                        self.is_grounded=false
                    }
                    this.frames-=game.dt
                    if(this.frames<0.2){
                        self.image="specialgrab1.png"
                    }
                    if(this.frames<=0){
                        this.frames=0
                        self.state="idle"
                    }
                }
            }
            opponent.states["being thrown"]={
                frames:0,
                offsetx:0,
                offsety:0,
                temps:{},
                update:function(self,game){
                    if(this.frames==0){
                        self.image="hit.png"
                        this.frames=0.6
                        self.vy=-600
                        self.vx=0
                        self.is_grounded=false
                    }
                    this.frames-=game.dt
                    if(this.frames<=0){
                        this.frames=0
                        self.health-=30
                        self.knockdown()
                    }
                }
            }
        }
    }
}

game.chars.push(griffon)

