let maki = {
    name: "maki",
    width: 64,
    height: 104,
    states:{
        "jump":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"jump0.png",duration:0.5},
                {image:"jump1.png",duration:0.5}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vx=200*self.direction
                self.vy=-800
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer=="attack"){
                    self.state="jump attack"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.state_buffer=="special 1"){
                    self.state="jump special"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:2,
            animations:[
                {image:"dash0.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash3.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){},
            update:function(self,game){
                self.vx=300*self.direction
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                }
            },
            end:function(game,obj,self){}
        },
        "back dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:2,
            animations:[
                {image:"backdash0.png",duration:0.1},
                {image:"backdash1.png",duration:0.1},
                {image:"backdash2.png",duration:0.1},
                {image:"backdash3.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){},
            update:function(self,game){
                self.vx=300*-self.direction
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                }
            },
            end:function(game,obj,self){}
        },
        "attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"attack0.png",duration:0.1},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0.1},
                {image:"attack2.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:100,h:10},
            init:function(game,obj,self){self.vx=0},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                if(self.state_buffer=="attack"){
                    self.state="attack2"
                    self.state_buffer="none"
                }
            }
        },
        "attack2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"attack20.png",duration:0.1},
                {image:"attack21.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0.1},
                {image:"attack22.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0.1},
                {image:"attack23.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:100,h:10},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                if(self.state_buffer=="attack"){
                    self.state="attack3"
                    self.state_buffer="none"
                }
            }
        },
         "attack3":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"attack30.png",duration:0.1},
                {image:"attack31.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0.1},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:true,stun:0.3,freeze_frame:0.2},
                {image:"attack33.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:100,h:10},
            init:function(game,obj,self){
                self.vy=-200
                self.vx=200*self.direction
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){self.vx=0}
        },
        "special 1":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"idle.png",duration:1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "special 2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.5,
            temps:{},
            animations:[
                {image:"special20.png",duration:0.1},
                {image:"special21.png",duration:0.1},
                {image:"special22.png",duration:0.1},
                {image:"special23.png",duration:0.1},
                {image:"special24.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.enable_physics=false
                this.temps.func=self.hit
                this.temps.direction=self.direction
                self.hit=function(){}
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                self.x+=250*this.temps.direction*game.dt
            },
            end:function(game,obj,self){
                self.enable_physics=true
                self.hit=this.temps.func
            }
        },
        "special 3":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"special30.png",duration:0.1},
                {image:"special31.png",duration:0.1,damage:10,knockback:-100,knockdown:false,freeze_frame:0.1},
                {image:"special32.png",duration:0.1},
                {image:"special33.png",duration:0.1,damage:10,knockback:-100,knockdown:false,freeze_frame:0.1},
                {image:"special34.png",duration:0.1},
                {image:"special31.png",duration:0.1,damage:10,knockback:-100,knockdown:false,freeze_frame:0.1},
                {image:"special32.png",duration:0.1},
                {image:"special33.png",duration:0.1,damage:10,knockback:-100,knockdown:true,freeze_frame:0.1},
                {image:"special34.png",duration:0.1},
                {image:"special30.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-64,y:-50,w:120,h:40},
            init:function(game,obj,self){
                self.vx=0
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "ultimate":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:2.2,
            animations:[
                {image:"attack0.png",duration:0.1},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack21.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        opponent.hit_max=0
                    }},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack22.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"dashspecial1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"special31.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"special31.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        opponent.hit_max=0
                    }
                },
                {image:"dashspecial1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack21.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"special31.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack22.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        opponent.hit_max=0
                    }},
                {image:"attack1.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"special31.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack22.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:false,stun:0.3,freeze_frame:0},
                {image:"attack32.png",duration:0.1,damage:5,knockback:0,knockdown:true,stun:0.3,freeze_frame:0.2},

            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:40,h:20},
            init:function(game,obj,self){
                self.vx=200*self.direction
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){self.vx=0}
        },
        "sweep":{},
        "jump special":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"idle.png",duration:1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "jump attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"jumpattack0.png",duration:0.1},
                {image:"jumpattack1.png",duration:0.2,damage:5,knockback:-100,knockdown:false,stun:0.5,freeze_frame:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:70,h:50},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "jump special":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"jumpspecial0.png",duration:0.1,custom:function(game,obj,self){
                    self.vx=0
                    self.vy=0
                }},
                {image:"jumpspecial1.png",duration:0.05,
                    custom:function(game,obj,self){
                        self.vx=300*self.direction
                        self.vy=300
                    }
                },
                {image:"jumpspecial1.png",duration:0.15,damage:5,knockback:-100,knockdown:false,stun:0.5,freeze_frame:0.1},
                {image:"jumpspecial1.png",duration:0.1,damage:5,knockback:-100,knockdown:false,stun:0.5,freeze_frame:0.1}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:70,h:50},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "example":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"idle.png",duration:1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
    }
}

game.chars.push(maki)

