let karin = {
    name: "karin",
    width: 88,
    height: 84,
    states:{
        "jump":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"jump0.png",duration:0.1},
                {image:"jump1.png",duration:0.1},
                {image:"jump2.png",duration:0.1},
                {image:"jump2.png",duration:0.1},
                {image:"jump1.png",duration:0.1},
                {image:"jump0.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vx=300*self.direction
                self.vy=-500
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer=="attack"){
                    self.state="jump attack"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:4,
            animations:[
                {image:"dash0.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash3.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){self.vx=150*self.direction},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    return
                }
            },
            end:function(game,obj,self){self.vx=0}
        },
        "back dash":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:4,
            animations:[
                {image:"dash3.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash0.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){self.vx=150*-self.direction},
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    return
                }
            },
            end:function(game,obj,self){self.vx=0}
        },
        "attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"attack.png",duration:0.1},
                {image:"attack.png",duration:0.1,damage:5,knockback:-50,stun:0.4},
                {image:"attack.png",duration:0.1}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:15,w:55,h:30},
            init:function(game,obj,self){
                self.vx=0
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                if(self.state_buffer=="attack"){
                    self.state="special 1 rekke2"
                    self.state_buffer="none"
                }
            }
        },
        "special 1":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"special10.png",duration:0.1},
                {image:"special11.png",duration:0.1,damage:5,knockback:-100},
                {image:"special12.png",duration:0.1,damage:5,knockback:-100,stun:0.5},
                {image:"special13.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:15,w:55,h:30},
            init:function(game,obj,self){
                self.vx=200*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
                if(self.state_buffer=="special 1"){
                    self.state="special 1 rekke1"
                    self.state_buffer="none"
                }
            }
        },
        "special 1 rekke1":{
           frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"special14.png",duration:0.1},
                {image:"special15.png",duration:0.1,damage:5,knockback:-100},
                {image:"special16.png",duration:0.1,damage:5,knockback:-100,stun:0.5},
                {image:"special17.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
             hitbox_data:{x:40,y:15,w:55,h:30},
            init:function(game,obj,self){
                self.vx=200*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
                if(self.state_buffer=="special 1"){
                    self.state="special 1 rekke2"
                    self.state_buffer="none"
                }
            }
        },
        "special 1 rekke2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"special18.png",duration:0.1},
                {image:"special19.png",duration:0.1,damage:15,knockdown:true},
                {image:"special110.png",duration:0.1,damage:15,knockdown:true},
                {image:"special111.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:15,w:55,h:30},
            init:function(game,obj,self){
                self.vx=200*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
            }
        },
        "special 2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.6,
            animations:[
                {image:"special20.png",duration:0.1},
                {image:"special21.png",duration:0.1},
                {image:"special22.png",duration:0.1,damage:5,
                    custom:function(game,obj,self){
                        game.playsound("assets/strike.wav")
                    }
                },
                {image:"special23.png",duration:0.1,damage:5,},
                {image:"special24.png",duration:0.1,damage:5,knockback:-200},
                {image:"special25.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:0,w:80,h:80},
            init:function(game,obj,self){
                self.vx=300*self.direction
                self.vy=-500
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "special 3":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.5,
            temps:{},
            animations:[
                {image:"special30.png",duration:0.1},
                {image:"special31.png",duration:0.1},
                {image:"special32.png",duration:0.1},
                {image:"special33.png",duration:0.1},
                {image:"special34.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.enable_physics=false
                this.temps.func=self.hit
                this.temps.direction=self.direction
                self.hit=function(){}
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                self.x+=250*this.temps.direction*game.dt
            },
            end:function(game,obj,self){
                self.enable_physics=true
                self.hit=this.temps.func
            }
        },
        "ultimate":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1,
            animations:[
                {image:"special10.png",duration:0.1},
                {image:"special11.png",duration:0.1,damage:10,knockback:-100},
                {image:"special12.png",duration:0.1,damage:10,knockback:-100,stun:0.5},
                {image:"special13.png",duration:0.1},
                {image:"special15.png",duration:0.1,damage:10,knockback:-100},
                {image:"special16.png",duration:0.1,damage:10,knockback:-100,stun:0.5},
                {image:"special17.png",duration:0.1},
                {image:"special19.png",duration:0.1,damage:10,knockdown:true},
                {image:"special110.png",duration:0.1,damage:10,knockdown:true},
                {image:"special111.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:15,w:55,h:30},
            init:function(game,obj,self){
                self.vx=200*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){
                self.vx=0
            }
        },
        "jump attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"jumpattack.png",duration:0.1},
                {image:"jumpattack.png",duration:0.1,damage:5,knockback:-50,stun:0.5},
                {image:"jumpattack.png",duration:0.1}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-20,y:40,w:140,h:40},
            init:function(game,obj,self){
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){self.vx=0}
        },
        "block":{
            update:function(self,game){
                self.vx=0
                self.image="block.png"
                if(self.state_buffer=="attack"){
                    self.state="sweep"
                    self.state_buffer="none"
                    return
                }
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                }
            }
        },
        "sweep":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.6,
            animations:[
                {image:"sweep0.png",duration:0.1,offset:{x:50,y:0}},
                {image:"sweep1.png",duration:0.1,offset:{x:50,y:0}},
                {image:"sweep2.png",duration:0.1,damage:10,knockdown:true,offset:{x:50,y:0}},
                {image:"sweep2.png",duration:0.1,damage:10,knockdown:true,offset:{x:50,y:0}},
                {image:"sweep1.png",duration:0.1,offset:{x:50,y:0}},
                {image:"sweep0.png",duration:0.1,offset:{x:50,y:0}},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:40,y:50,w:80+50,h:30},
            init:function(game,obj,self){
                self.vx=0
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
    }
}

game.chars.push(karin)

