let chunli = {
    name: "chunli",
    width: 60,
    height: 96,
    states:{
        "jump":{
             frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:5,
            animations:[
                {image:"jump0.png",duration:0.1},
                {image:"jump2.png",duration:0.1},
                //{image:"jump3.png",duration:0.1},
                {image:"jump4.png",duration:0.1},
                {image:"jump5.png",duration:0.1},
                {image:"jump6.png",duration:0.1},
                {image:"jump7.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:0,y:0,w:0,h:0},
            init:function(game,obj,self){
                self.vy=-700
                self.is_grounded=false
                game.playsound("assets/jump.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer=="attack"){
                    self.state="jump attack"
                    self.state_buffer="none"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    return
                }
                if(self.is_grounded==true){
                    self.state="idle"
                    this.anim_frame_count=0
                    this.animation_frame=0
                    this.frames=0
                    self.vx=0
                    self.vy=0
                }
            },
            end:function(game,obj,self){
                self.vx=0
                self.vy=0
            }
        },
        "dash":{
            frames:0,
            hitbox:{x:0,y:0,w:0,h:0},
            animation_frame:0,
            anim_frame_count:0,
            animations:[
                {image:"dash0.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash3.png",duration:0.1},
                {image:"dash4.png",duration:0.1},
                {image:"dash5.png",duration:0.1},
                {image:"dash6.png",duration:0.1},
                {image:"dash7.png",duration:0.1},
                {image:"dash8.png",duration:0.1}
            ],
            offsetx:0,
            offsety:0,
            update:function(self,game){
                if(this.frames==0){
                    this.frames=4//1 second
                    self.vx=150*self.direction
                }
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    return
                }
                self.image=this.animations[this.animation_frame].image
                this.anim_frame_count+=game.dt
                if(this.anim_frame_count>=this.animations[this.animation_frame].duration){
                    this.animation_frame=(this.animation_frame+1)%this.animations.length
                    this.anim_frame_count=0
                }
                this.frames-=game.dt
                if(this.frames<=0){
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    self.vx=0
                    self.state="idle"
                }
            }
        },
        "back dash":{
            frames:0,
            hitbox:{x:0,y:0,w:0,h:0},
            animation_frame:0,
            anim_frame_count:0,
            animations:[
                {image:"dash8.png",duration:0.1},
                {image:"dash7.png",duration:0.1},
                {image:"dash6.png",duration:0.1},
                {image:"dash5.png",duration:0.1},
                {image:"dash4.png",duration:0.1},
                {image:"dash3.png",duration:0.1},
                {image:"dash2.png",duration:0.1},
                {image:"dash1.png",duration:0.1},
                {image:"dash0.png",duration:0.1},

            ],
            offsetx:0,
            offsety:0,
            update:function(self,game){
                if(this.frames==0){
                    this.frames=4//1 second
                    self.vx=100*-self.direction
                }
                if(self.state_buffer!="none"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    return
                }
                self.image=this.animations[this.animation_frame].image
                this.anim_frame_count+=game.dt
                if(this.anim_frame_count>=this.animations[this.animation_frame].duration){
                    this.animation_frame=(this.animation_frame+1)%this.animations.length
                    this.anim_frame_count=0
                }
                this.frames-=game.dt
                if(this.frames<=0){
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    self.vx=0
                    self.state="idle"
                }
            }
        },
        "attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.3,
            animations:[
                {image:"attack.png",duration:0.1,offset:{x:50,y:0}},
                {image:"attack.png",duration:0.1,damage:5,offset:{x:50,y:0},stun:0.4,knockback:-100},
                {image:"attack.png",duration:0.1,offset:{x:50,y:0}}
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:30,y:-30,w:80,h:40},
            init:function(game,obj,self){
                if(self.is_grounded==true){
                    self.vx=0
                }
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
                if(self.state_buffer!="none"&&self.state_buffer!="attack"){
                    let x = self.state_buffer
                    self.state=x
                    self.state_buffer="none"
                    this.frames=0
                    this.anim_frame_count=0
                    this.animation_frame=0
                    return
                }
            },
            end:function(game,obj,self){}
        },
        "special 1":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            animations:[
                {image:"special1.png",duration:0.2},
                {image:"special1.png",duration:0.06},
                {image:"special1.png",duration:0.3-0.06},],
            update:function(self,game){
                if(this.frames==0){
                     if(self.is_grounded==true){
                        self.vx=0
                    }
                    this.frames=0.5//1 second
                }
                self.image=this.animations[this.animation_frame].image
                this.anim_frame_count+=game.dt
                if(this.anim_frame_count>=this.animations[this.animation_frame].duration){
                    this.animation_frame=(this.animation_frame+1)%this.animations.length
                    if(this.animation_frame==1){
                        let fire_ball = {
                            id:`fireball ${self.id}`,
                            x:self.x+50*self.direction,
                            y:self.y+20,
                            w:30,
                            h:30,
                            direction:self.direction,
                            frames:3,
                            user:self,
                            target:game.match.get_opponent(self,game),
                            animation_frame:0,
                            anim_frame_count:0,
                            animations:[
                                {duration:0.1},
                                 {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                                {duration:0.1},
                            ],
                            update:function(self,game){
                                this.x+=this.direction*100*game.dt
                                let opponent=this.target
                                if(game.physics.aabb(this,opponent,game)){
                                    opponent.hit(10,this.user,game)
                                    this.frames=0
                                    let index = self.objects.indexOf(this)
                                    if (index > -1) {
                                        self.objects.splice(index, 1);
                                    }
                                }
                                this.frames-=game.dt
                                if(this.frames<=0){
                                    this.frames=0
                                    let index = self.objects.indexOf(this)
                                    if (index > -1) {
                                        self.objects.splice(index, 1);
                                    }
                                }
                            },
                            render:function(self,game){
                                let ctx = game.ctx
                                let canvas = game.canvas
                                let img = new Image()
                                let actor=this
                                let center = {x:this.x+this.w/2,y:this.y+this.h/2}
                                img.src=`chars/sakura/sprites/hadoken${this.animation_frame}.png`
                                this.anim_frame_count+=game.dt
                                if(this.anim_frame_count>=this.animations[this.animation_frame].duration){
                                    this.animation_frame=(this.animation_frame+1)%this.animations.length
                                    this.anim_frame_count=0
                                }
                                ctx.save();
                                if (actor.direction === -1) {
                                    ctx.translate(actor.x + actor.w, actor.y);
                                    ctx.scale(-1, 1);
                                    ctx.drawImage(img, (this.w/2)-img.width/2, (this.h/2)-img.height/2);
                                } else {
                                    ctx.translate(actor.x, actor.y);
                                    ctx.drawImage(img, (this.w/2)-img.width/2, (this.h/2)-img.height/2);
                                }
                                ctx.restore(); 
                                ctx.strokeStyle="orange"
                                ctx.strokeRect(this.x,this.y,this.w,this.h)
                            }
                        }
                        if (!self.objects.some(obj => obj.id === fire_ball.id)) {
                            self.objects.push(fire_ball);
                        }
                    }
                    this.anim_frame_count=0
                }
                this.frames-=game.dt
                if(this.frames<=0){
                    this.frames=0
                    self.state="idle"
                }
            }
        },
        "special 2":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1.2,
            animations:[
                {image:"special21.png",duration:0.1},
                {image:"special21.png",duration:0.1,
                    custom:function(game,obj,self){
                        self.vx=0
                    }
                },
                {image:"special20.png",duration:0.1,damage:5,knockback:0},
                {image:"special21.png",duration:0.1},
                {image:"special22.png",duration:0.1,damage:5,knockback:0},
                {image:"special21.png",duration:0.1},
                {image:"special23.png",duration:0.1,damage:5,knockback:0,stun:0.4},
                {image:"special21.png",duration:0.1},
                {image:"special21.png",duration:0.1},
                {image:"special24.png",duration:0.1,damage:10,knockback:-300,knockdown:true},
                {image:"special24.png",duration:0.1,damage:10,knockback:-300,knockdown:true},
                {image:"special24.png",duration:0.1,damage:10,knockback:-300,knockdown:true},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-10,y:-15,w:80,h:30},
            init:function(game,obj,self){
                self.vx=400*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
        "special 3":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:1.65,
            animations:[
                {image:"special30.png",duration:0.1},
                {image:"special31.png",duration:0.05},
                {image:"special32.png",duration:0.1},
                {image:"special33.png",duration:0.1,damage:4,knockback:-50,stun:0.3},
                {image:"special34.png",duration:0.1},
                {image:"special35.png",duration:0.1,damage:4,knockback:-50,stun:0.3},
                {image:"special36.png",duration:0.1},
                {image:"special37.png",duration:0.1,damage:4,knockback:-50,stun:0.3},
                {image:"special33.png",duration:0.1},
                {image:"special34.png",duration:0.1,damage:4,knockback:-50,stun:0.3},
                {image:"special35.png",duration:0.1},
                {image:"special36.png",duration:0.1,damage:4,knockback:-50,stun:0.3},
                {image:"special37.png",duration:0.1},
                {image:"special33.png",duration:0.1,damage:10,knockback:-200,stun:0.3},
                {image:"special38.png",duration:0.1},
                {image:"special39.png",duration:0.1},
                {image:"special310.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-30,y:-40,w:100,h:30},
            init:function(game,obj,self){
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                self.vx=250*self.direction
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){self.vx=0}
        },
        "ultimate":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:2.1,
            animations:[
                {image:"special21.png",duration:0.2},
                {image:"special22.png",duration:0.1,damage:5,
                    custom:function(game,obj,self){
                        game.playsound("assets/strike.wav")
                        self.vx=0
                    }
                },
                {image:"special21.png",duration:0.1},
                {image:"special20.png",duration:0.1,damage:5},
                {image:"special21.png",duration:0.1},
                {image:"special23.png",duration:0.1,damage:5},
                {image:"special21.png",duration:0.1},
                {image:"special22.png",duration:0.1,damage:5,knockback:-300,stun:0.5},
                {image:"special21.png",duration:0.2,
                    custom:function(game,obj,self){
                        self.vx=400*self.direction
                    }
                },
                {image:"special20.png",duration:0.1,damage:5,
                    custom:function(game,obj,self){
                        game.playsound("assets/strike.wav")
                        self.vx=0
                    }},
                {image:"special21.png",duration:0.1},
                {image:"special23.png",duration:0.1,damage:5},
                {image:"special21.png",duration:0.1},
                {image:"special22.png",duration:0.1,damage:5},
                {image:"special21.png",duration:0.1},
                {image:"special20.png",duration:0.1,damage:5,knockback:-300,stun:0.5},
                {image:"special21.png",duration:0.2,
                    custom:function(game,obj,self){
                        self.vx=400*self.direction
                    }
                },
                {image:"special24.png",duration:0.1,damage:10,knockback:-300,knockdown:true,
                    custom:function(game,obj,self){
                        game.playsound("assets/strike.wav")
                        self.vx=0
                    },stun:0.5
                },
                {image:"special24.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-30,y:-40,w:100,h:30},
            init:function(game,obj,self){
                self.vx=400*self.direction
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){self.vx=0}
        },
        "jump attack":{
            frames:0,
            animation_frame:0,
            anim_frame_count:0,
            hitbox:{x:0,y:0,w:0,h:0},
            total_frames:0.4,
            animations:[
                {image:"jumpattack.png",duration:0.1},
                {image:"jumpattack.png",duration:0.1,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        if(game.physics.aabb(obj.hitbox,opponent,game)){
                            opponent.damage({
                                damage:5,
                                knockback:0,
                                knockdown:false,
                                stun:0.2
                            },game)
                            self.vy=-700
                        }
                    }
                },
                {image:"jumpattack.png",duration:0.1,
                    custom:function(game,obj,self){
                        let opponent=game.match.get_opponent(self,game)
                        if(game.physics.aabb(obj.hitbox,opponent,game)){
                            opponent.damage({
                                damage:5,
                                knockback:0,
                                knockdown:false,
                                stun:0.2
                            },game)
                            self.vy=-700
                        }
                    }
                },
                {image:"jumpattack.png",duration:0.1},
            ],
            offsetx:0,
            offsety:0,
            hitbox_data:{x:-20,y:40,w:40,h:30},
            init:function(game,obj,self){
                game.playsound("assets/strike.wav")
            },
            update:function(self,game){
                game.battle_engine.update_animation(game,this,self)
            },
            end:function(game,obj,self){}
        },
    }
}

game.chars.push(chunli)